using System; using System.Diagnostics; using System.IO; using System.Media; using System.Windows; using System.Windows.Media; using System.Windows.Media.Imaging; using Google.Apis.Calendar.v3.Data;
namespace LichNhac;
public partial class MainWindow : Window
{
 private string _asset = "mochi"; private string _character = "Mochi";
 public MainWindow() { InitializeComponent(); SetCharacter("mochi", "Mochi", "Mèo mây", "#2563EB"); }
 private void CharacterPicker_Changed(object sender, System.Windows.Controls.SelectionChangedEventArgs e) { if (CharacterPicker.SelectedItem is not System.Windows.Controls.ComboBoxItem item) return; var tag = item.Tag?.ToString() ?? "mochi"; var parts = item.Content?.ToString()?.Split('•') ?? ["Mochi", "Mèo mây"]; var colors = new Dictionary<string,string> { ["mochi"]="#2563EB", ["luna"]="#7C3AED", ["bobo"]="#D97706", ["mam"]="#059669" }; SetCharacter(tag, parts[0].Trim(), parts.Length > 1 ? parts[1].Trim() : "", colors[tag]); }
 private void SetCharacter(string asset, string name, string type, string color) { _asset = asset; _character = name; CharacterName.Text = $"{name} • {type}"; CharacterImage.Source = new BitmapImage(new Uri($"pack://application:,,,/assets/{asset}.png")); var c = (Color)ColorConverter.ConvertFromString(color); CharacterCard.Background = new SolidColorBrush(Color.FromArgb(28, c.R, c.G, c.B)); }
 private void Test_Click(object sender, RoutedEventArgs e) { var seconds = int.TryParse(DurationBox.Text, out var value) ? Math.Clamp(value, 3, 120) : 8; DurationBox.Text = seconds.ToString(); new ReminderWindow(_character, _asset, "14:30 • Họp nhóm thiết kế", seconds).Show(); if (SoundToggle.IsChecked == true) SystemSounds.Asterisk.Play(); }
 private async void Connect_Click(object sender, RoutedEventArgs e) { var credentials = Path.Combine(AppContext.BaseDirectory, "credentials.json"); if (!File.Exists(credentials)) { ConnectionStatus.Text = "Thiếu credentials.json"; ConnectionStatus.Foreground = new SolidColorBrush(Color.FromRgb(220,38,38)); MessageBox.Show("Để đăng nhập Google Calendar thật:\n\n1. Tạo OAuth Desktop Client trong Google Cloud Console.\n2. Tải JSON về và đổi tên thành credentials.json.\n3. Đặt cạnh MayNhac.exe.\n4. Bấm nút này lại để mở đăng nhập Google và cấp quyền đọc lịch.", "Cần cấu hình Google Calendar", MessageBoxButton.OK, MessageBoxImage.Information); Process.Start(new ProcessStartInfo("https://console.cloud.google.com/apis/credentials") { UseShellExecute = true }); return; } ConnectButton.IsEnabled = false; ConnectionStatus.Text = "Đang mở đăng nhập Google..."; try { var events = await new GoogleCalendarService().SignInAndListAsync(); ConnectionStatus.Text = $"Đã kết nối • {events.Count} lịch trong 7 ngày"; ConnectionStatus.Foreground = new SolidColorBrush(Color.FromRgb(5,150,105)); ConnectButton.Content = "Đã kết nối"; EventOne.Text = FormatEvent(events.ElementAtOrDefault(0), "Chưa có lịch sắp tới"); EventTwo.Text = FormatEvent(events.ElementAtOrDefault(1), "Thêm lịch trong Google Calendar"); } catch (Exception ex) { ConnectionStatus.Text = "Đăng nhập thất bại"; ConnectionStatus.Foreground = new SolidColorBrush(Color.FromRgb(220,38,38)); MessageBox.Show(ex.Message, "Google Calendar", MessageBoxButton.OK, MessageBoxImage.Warning); ConnectButton.IsEnabled = true; } }
 private static string FormatEvent(Event? item, string fallback) { if (item == null) return fallback; var start = item.Start?.DateTimeDateTimeOffset?.ToLocalTime().ToString("HH:mm") ?? item.Start?.Date ?? "--:--"; return $"{start}  •  {item.Summary ?? "Lịch không có tiêu đề"}"; }
}
