using System.Windows; using System.Windows.Media; using System.Windows.Media.Animation; using System.Windows.Media.Imaging;
namespace LichNhac;
public partial class ReminderWindow : Window
{
 private readonly int _seconds; private readonly string _asset;
 public ReminderWindow(string character, string asset, string message, int seconds) { InitializeComponent(); _asset = asset; Character.Text = character; Message.Text = message; FaceImage.Source = new BitmapImage(new Uri($"pack://application:,,,/assets/{asset}.png")); _seconds = seconds; }
 private async void OnLoaded(object sender, RoutedEventArgs e) { var area = SystemParameters.WorkArea; Left = area.Left + 18; Top = area.Bottom - Height - 18; BeginAnimation(OpacityProperty, new DoubleAnimation(0, 1, TimeSpan.FromMilliseconds(260))); PlayCharacterAnimation(); await Task.Delay(_seconds * 1000); CloseAnimated(); }
 private void PlayCharacterAnimation() { var ease = new CubicEase { EasingMode = EasingMode.EaseOut }; var move = new DoubleAnimation { From = -70, To = 0, Duration = TimeSpan.FromMilliseconds(420), EasingFunction = ease }; FaceMove.BeginAnimation(TranslateTransform.XProperty, move); if (_asset == "luna") { FaceRotate.BeginAnimation(RotateTransform.AngleProperty, new DoubleAnimation(-12, 0, TimeSpan.FromMilliseconds(520)) { EasingFunction = ease }); } else if (_asset == "bobo") { var bounce = new DoubleAnimationUsingKeyFrames(); bounce.KeyFrames.Add(new EasingDoubleKeyFrame(-18, KeyTime.FromTimeSpan(TimeSpan.FromMilliseconds(160)), ease)); bounce.KeyFrames.Add(new EasingDoubleKeyFrame(0, KeyTime.FromTimeSpan(TimeSpan.FromMilliseconds(340)), ease)); FaceMove.BeginAnimation(TranslateTransform.YProperty, bounce); } else if (_asset == "mam") { FaceScale.BeginAnimation(ScaleTransform.ScaleXProperty, new DoubleAnimation(0.55, 1, TimeSpan.FromMilliseconds(420)) { EasingFunction = ease }); FaceScale.BeginAnimation(ScaleTransform.ScaleYProperty, new DoubleAnimation(0.55, 1, TimeSpan.FromMilliseconds(420)) { EasingFunction = ease }); } else { var floatAnim = new DoubleAnimationUsingKeyFrames { RepeatBehavior = RepeatBehavior.Forever, AutoReverse = true }; floatAnim.KeyFrames.Add(new EasingDoubleKeyFrame(-4, KeyTime.FromTimeSpan(TimeSpan.FromMilliseconds(900)), ease)); floatAnim.KeyFrames.Add(new EasingDoubleKeyFrame(0, KeyTime.FromTimeSpan(TimeSpan.FromMilliseconds(1800)), ease)); FaceMove.BeginAnimation(TranslateTransform.YProperty, floatAnim); } }
 private void Close_Click(object sender, RoutedEventArgs e) => CloseAnimated(); private void CloseAnimated() { var animation = new DoubleAnimation(1, 0, TimeSpan.FromMilliseconds(180)); animation.Completed += (_, _) => Close(); BeginAnimation(OpacityProperty, animation); }
}
