using System.Runtime.InteropServices; using System.Windows; using System.Windows.Interop; using System.Windows.Media; using System.Windows.Media.Animation; using System.Windows.Media.Imaging;
namespace LichNhac;
public partial class ReminderWindow : Window
{
 private const int GWL_EXSTYLE = -20, WS_EX_NOACTIVATE = 0x08000000, WS_EX_TOOLWINDOW = 0x00000080, WM_MOUSEACTIVATE = 0x0021, MA_NOACTIVATE = 3; private readonly int _seconds; private readonly string _asset;
 public ReminderWindow(string character, string asset, string message, int seconds) { InitializeComponent(); _asset = asset; Character.Text = character; Message.Text = message; FaceImage.Source = new BitmapImage(new Uri($"pack://application:,,,/assets/{asset}.png")); _seconds = seconds; SourceInitialized += (_, _) => MakeNonActivating(); }
 private void MakeNonActivating() { var hwnd = new WindowInteropHelper(this).Handle; var source = HwndSource.FromHwnd(hwnd); var style = GetWindowLongPtr(hwnd, GWL_EXSTYLE).ToInt64(); SetWindowLongPtr(hwnd, GWL_EXSTYLE, new IntPtr(style | WS_EX_NOACTIVATE | WS_EX_TOOLWINDOW)); source?.AddHook((IntPtr hookHwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled) => { if (msg == WM_MOUSEACTIVATE) { handled = true; return new IntPtr(MA_NOACTIVATE); } return IntPtr.Zero; }); }
 private async void OnLoaded(object sender, RoutedEventArgs e) { var area = SystemParameters.WorkArea; Left = area.Left + 18; Top = area.Bottom - Height - 18; BeginAnimation(OpacityProperty, new DoubleAnimation(0, 1, TimeSpan.FromMilliseconds(260))); PlayCharacterAnimation(); await Task.Delay(_seconds * 1000); CloseAnimated(); }
 private void PlayCharacterAnimation() { var ease = new CubicEase { EasingMode = EasingMode.EaseOut }; FaceMove.BeginAnimation(TranslateTransform.XProperty, new DoubleAnimation(-70, 0, TimeSpan.FromMilliseconds(420)) { EasingFunction = ease }); if (_asset == "luna") FaceRotate.BeginAnimation(RotateTransform.AngleProperty, new DoubleAnimation(-12, 0, TimeSpan.FromMilliseconds(520)) { EasingFunction = ease }); else if (_asset == "bobo") { var bounce = new DoubleAnimationUsingKeyFrames(); bounce.KeyFrames.Add(new EasingDoubleKeyFrame(-18, KeyTime.FromTimeSpan(TimeSpan.FromMilliseconds(160)), ease)); bounce.KeyFrames.Add(new EasingDoubleKeyFrame(0, KeyTime.FromTimeSpan(TimeSpan.FromMilliseconds(340)), ease)); FaceMove.BeginAnimation(TranslateTransform.YProperty, bounce); } else if (_asset == "mam") { FaceScale.BeginAnimation(ScaleTransform.ScaleXProperty, new DoubleAnimation(0.55, 1, TimeSpan.FromMilliseconds(420)) { EasingFunction = ease }); FaceScale.BeginAnimation(ScaleTransform.ScaleYProperty, new DoubleAnimation(0.55, 1, TimeSpan.FromMilliseconds(420)) { EasingFunction = ease }); } else { var floatAnim = new DoubleAnimationUsingKeyFrames { RepeatBehavior = RepeatBehavior.Forever, AutoReverse = true }; floatAnim.KeyFrames.Add(new EasingDoubleKeyFrame(-4, KeyTime.FromTimeSpan(TimeSpan.FromMilliseconds(900)), ease)); floatAnim.KeyFrames.Add(new EasingDoubleKeyFrame(0, KeyTime.FromTimeSpan(TimeSpan.FromMilliseconds(1800)), ease)); FaceMove.BeginAnimation(TranslateTransform.YProperty, floatAnim); } }
 private void Close_Click(object sender, RoutedEventArgs e) => CloseAnimated(); private void CloseAnimated() { var animation = new DoubleAnimation(1, 0, TimeSpan.FromMilliseconds(180)); animation.Completed += (_, _) => Close(); BeginAnimation(OpacityProperty, animation); }
 [DllImport("user32.dll", EntryPoint="GetWindowLongPtrW")] private static extern IntPtr GetWindowLongPtr64(IntPtr hWnd, int nIndex); [DllImport("user32.dll", EntryPoint="SetWindowLongPtrW")] private static extern IntPtr SetWindowLongPtr64(IntPtr hWnd, int nIndex, IntPtr dwNewLong); private static IntPtr GetWindowLongPtr(IntPtr hWnd, int nIndex) => IntPtr.Size == 8 ? GetWindowLongPtr64(hWnd, nIndex) : new IntPtr(GetWindowLongPtr32(hWnd, nIndex).ToInt32()); private static IntPtr SetWindowLongPtr(IntPtr hWnd, int nIndex, IntPtr value) => IntPtr.Size == 8 ? SetWindowLongPtr64(hWnd, nIndex, value) : new IntPtr(SetWindowLongPtr32(hWnd, nIndex, value.ToInt32())); [DllImport("user32.dll", EntryPoint="GetWindowLongW")] private static extern IntPtr GetWindowLongPtr32(IntPtr hWnd, int nIndex); [DllImport("user32.dll", EntryPoint="SetWindowLongW")] private static extern IntPtr SetWindowLongPtr32(IntPtr hWnd, int nIndex, int dwNewLong);
}
